### ISSUE TITLE
US#119 - Tsk#04 - Teste de Critérios de Aceitação e casos de testes

### ISSUE THREAD

**Issue by engcompjuliana** [stagioptr/ipbl2019#169]

**Comment by LexDias** [comment]
Testes realizados no protótipo criado na [Tsk#05](https://github.com/stagioptr/ipbl2019/issues/175), de acordo com os requisitos especificados na [Planilha de Testes](https://docs.google.com/spreadsheets/d/1umU-lbmSLOwHid19a9TyVebW9q1k9Op6/edit#gid=1778864658).

Evidência: [Vídeo da execução da Rotina 01](http://t.ly/ORAJ7)
